services:
  postgres:
    image: postgres:16
    container_name: myproject-postgres
    restart: always
    environment:
      POSTGRES_USER: prismatest
      POSTGRES_PASSWORD: prismatest
      POSTGRES_DB: products_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: